version: '3'
services:
  nginx:
    image: "nginx-gatuk"
    volumes:
     - ./conf.d:/etc/nginx/conf.d
     - ./static:/usr/share/nginx/html
    ports:
     - "8080:80"
    command: "nginx -g 'daemon off;'"
